#!/usr/bin/env ruby
# File: script/console
irb = RUBY_PLATFORM =~ /(:?mswin|mingw)/ ? 'irb.bat' : 'irb'

libs = " -r irb/completion"
libs = " -r ruby-debug"
# Perhaps use a console_lib to store any extra methods I may want available in the cosole
# libs << " -r #{File.dirname(__FILE__) + '/../lib/console_lib/console_logger.rb'}"
libs <<  " -r #{File.dirname(__FILE__) + '/../lib/couch_crumbs.rb'}"
puts "Loading couch_crumbs gem"
exec "#{irb} #{libs} --simple-prompt"